import {
  LayoutDashboard,
  Users,
  UserCircle,
  Building2,
  Shield,
  Upload,
  Settings,
  Layout,
  FileText,
  BarChart2,
  ShoppingCart,
  Package,
  Truck,
  ClipboardList,
  Bell,
  Lock,
  Globe,
  Mail,
  Calendar,
  Map,
  Tag,
  Layers,
  type LucideIcon,
} from 'lucide-react'

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: 'LayoutDashboard', icon: LayoutDashboard },
  { name: 'Users',           icon: Users           },
  { name: 'UserCircle',      icon: UserCircle      },
  { name: 'Building2',       icon: Building2       },
  { name: 'Shield',          icon: Shield          },
  { name: 'Upload',          icon: Upload          },
  { name: 'Settings',        icon: Settings        },
  { name: 'Layout',          icon: Layout          },
  { name: 'FileText',        icon: FileText        },
  { name: 'BarChart2',       icon: BarChart2       },
  { name: 'ShoppingCart',    icon: ShoppingCart    },
  { name: 'Package',         icon: Package         },
  { name: 'Truck',           icon: Truck           },
  { name: 'ClipboardList',   icon: ClipboardList   },
  { name: 'Bell',            icon: Bell            },
  { name: 'Lock',            icon: Lock            },
  { name: 'Globe',           icon: Globe           },
  { name: 'Mail',            icon: Mail            },
  { name: 'Calendar',        icon: Calendar        },
  { name: 'Map',             icon: Map             },
  { name: 'Tag',             icon: Tag             },
  { name: 'Layers',          icon: Layers          },
]

export function getIcon(name: string): LucideIcon {
  return ICON_OPTIONS.find((o) => o.name === name)?.icon ?? FileText
}
