/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutUploadRouteImport } from './routes/_layout/upload'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRolesRouteImport } from './routes/_layout/roles'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutPagesRouteImport } from './routes/_layout/pages'
import { Route as LayoutBranchesRouteImport } from './routes/_layout/branches'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUploadRoute = LayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutRolesRoute = LayoutRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutPagesRoute = LayoutPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutBranchesRoute = LayoutBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/branches': typeof LayoutBranchesRoute
  '/pages': typeof LayoutPagesRoute
  '/products': typeof LayoutProductsRoute
  '/profile': typeof LayoutProfileRoute
  '/roles': typeof LayoutRolesRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/users': typeof LayoutUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/branches': typeof LayoutBranchesRoute
  '/pages': typeof LayoutPagesRoute
  '/products': typeof LayoutProductsRoute
  '/profile': typeof LayoutProfileRoute
  '/roles': typeof LayoutRolesRoute
  '/settings': typeof LayoutSettingsRoute
  '/upload': typeof LayoutUploadRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/branches': typeof LayoutBranchesRoute
  '/_layout/pages': typeof LayoutPagesRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/roles': typeof LayoutRolesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/upload': typeof LayoutUploadRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/branches'
    | '/pages'
    | '/products'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/upload'
    | '/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/branches'
    | '/pages'
    | '/products'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/upload'
    | '/users'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/branches'
    | '/_layout/pages'
    | '/_layout/products'
    | '/_layout/profile'
    | '/_layout/roles'
    | '/_layout/settings'
    | '/_layout/upload'
    | '/_layout/users'
    | '/_layout/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/roles': {
      id: '/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof LayoutRolesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/pages': {
      id: '/_layout/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof LayoutPagesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/branches': {
      id: '/_layout/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof LayoutBranchesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutBranchesRoute: typeof LayoutBranchesRoute
  LayoutPagesRoute: typeof LayoutPagesRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutRolesRoute: typeof LayoutRolesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutBranchesRoute: LayoutBranchesRoute,
  LayoutPagesRoute: LayoutPagesRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutRolesRoute: LayoutRolesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUploadRoute: LayoutUploadRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
